#+title: Install Instructions

Some brief instructions for when I need to boot things onto a new computer.

* NixOS Setup (Using disko + flakes)

1. Boot into NixOS installer ISO (Minimal ISO is fine)
2. Connect to WiFi:
   #+begin_src bash
   iwctl station wlan0 connect "SSID"
   #+end_src

3. Clone the dotfiles repo:
   #+begin_src bash
   git clone https://github.com/dimitri-lopez/nixos-config ~/.dotfiles
   cd ~/.dotfiles
   #+end_src

4. Run the new host bootstrap script:
   #+begin_src bash
   python3 new-host.py <hostname>
   #+end_src
   This creates hosts/<hostname>/, copies the hardware config, and registers it.

5. Edit the per-host config to set swap UUID and add any quirks:
   #+begin_src bash
   vim hosts/<hostname>/default.org
   #+end_src

6. Partition with disko:
   #+begin_src bash
   sudo nix run github:nix-community/disko -- --mode disko hosts/<hostname>/disko-config.nix
   #+end_src

7. Tangle and install:
   #+begin_src bash
   python3 tangle.py readme.org
   sudo nixos-install --flake .#<hostname>
   #+end_src

8. Set root password, reboot, and login.

* Next steps

** Brave
1. Login to Google
2. Login to Bitwarden (will need this for pulling down personal emacs config)
3. Launch and login to Dropbox
4. Sync Brave with phone
5. Bookmarks are under ~/.dotfiles/modules/brave-bookmarks.html

** Dropbox
Launch from the CLI (SUPER + T):
#+begin_src bash
dropbox &
#+end_src

When prompted login to the web browser. I have found that syncing over all of my files can take a couple of hours. Throw it on in the background and it should be fine.

After adding the autostart script, this won't be needed

** Doom Emacs
#+begin_src bash
# or run doom-git-clone-doom-repo-and-install
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src

I found that I would still boot into vanilla emacs. I had to move ~/.emacs.d to ~/.config/emacs
#+begin_src bash
mv ~/.emacs.d ~/.config/emacs
#+end_src

Then finally pull down my personal doom config repo. My personal access token can be found within Bitwarden.
#+begin_src bash
# doom-git-clone-personal-repo-and-install
rm -rf ~/.config/doom
git clone https://github.com/dimitri-lopez/.doom.d.git ~/.config/doom
cd ~/.config/doom
~/.config/emacs/bin/doom sync
~/.config/emacs/bin/doom doctor
echo "Check out ~/.dotfiles/install.org"
#+end_src

Then there are a couple of other things to run within emacs:
#+begin_src emacs-lisp
(nerd-icons-install-fonts)
(vterm-module-compile)
(copilot-install-server)
(copilot-login)
(pdf-tools-install)
#+end_src

** Online accounts to login to
- Google
- Bitwarden
- Dropbox
- Slack
- Outlook
- Discord
