#!/usr/bin/env python3
"""new-host.py — Bootstrap a new NixOS host config.

Usage:
  ./new-host.py <hostname>

Creates a host directory under hosts/<hostname>/, copies the current
hardware-configuration.nix, writes a default.org template, and registers
it in the flake and hosts/default.org.
"""

import argparse
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).parent.resolve()
HOSTS_DIR = REPO / "hosts"
FLAKE_ORG = REPO / "flake.org"
HOSTS_ORG = HOSTS_DIR / "default.org"
HARDWARE_SOURCE = pathlib.Path("/etc/nixos/hardware-configuration.nix")


def main():
    parser = argparse.ArgumentParser(description="Bootstrap a new NixOS host config")
    parser.add_argument("hostname", help="Name of the new host (e.g. x13)")
    args = parser.parse_args()

    hostname = args.hostname
    host_dir = HOSTS_DIR / hostname
    host_org = host_dir / "default.org"
    host_nix = host_dir / "default.nix"
    hw_target = host_dir / "hardware-configuration.nix"

    if host_dir.exists():
        print(f"Error: Host '{hostname}' already exists at {host_dir}")
        sys.exit(1)

    host_dir.mkdir(parents=True)

    # 1. Copy hardware config
    if HARDWARE_SOURCE.exists():
        import shutil
        shutil.copy2(HARDWARE_SOURCE, hw_target)
        print(f"  Copied {HARDWARE_SOURCE} → {hw_target}")
    else:
        hw_target.write_text("# hardware-configuration.nix — generated by nixos-generate-config\n")
        print(f"  Warning: {HARDWARE_SOURCE} not found, created placeholder")

    # 2. Write default.org template
    host_org.write_text(f"""\
#+title: {hostname} Configuration
#+begin_src nix :tangle ./hosts/{hostname}/default.nix
{{ modulesPath, inputs, ... }}: {{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ./hardware-configuration.nix
    ../../configuration.nix
    # TODO: add WM system module, e.g. ../../modules/driftwm/system.nix
  ];

  networking.hostName = "{hostname}";

  # TODO: add swap UUID
  # boot.resumeDevice = "/dev/disk/by-uuid/...";
  # boot.kernelParams = [ "resume=UUID=..." ];
}}
#+end_src
""")
    print(f"  Created {host_org}")

    # 3. Register in flake.org
    flake_text = FLAKE_ORG.read_text()
    # Insert a new host entry before the closing "}" of nixosConfigurations
    insertion = f'''  {hostname} = lib.nixosSystem {{
            inherit system;
            modules = [ ./hosts/{hostname} ];
            specialArgs = {{ inherit inputs; }};
          }};
'''
    # Find the nixosConfigurations block and insert before its closing brace
    import re
    pattern = r'(nixosConfigurations\s*=\s*\{[^}]*)(\n\s+\};)(\s+\};)'
    match = re.search(pattern, flake_text, re.DOTALL)
    if match:
        new_text = flake_text[:match.end(1)] + "\n" + insertion + flake_text[match.start(2):]
        FLAKE_ORG.write_text(new_text)
        print(f"  Registered in flake.org")
    else:
        print(f"  Warning: could not find nixosConfigurations block in flake.org")

    # 4. Register in hosts/default.org
    with HOSTS_ORG.open("a") as f:
        f.write(f"#+INCLUDE: ./{hostname}/default.org\n")
    print(f"  Registered in hosts/default.org")

    print(f"\nHost '{hostname}' created at {host_dir}")
    print("Next steps:")
    print(f"  1. Edit hosts/{hostname}/default.org — set swap UUID, add WM, add quirks")
    print(f"  2. python3 tangle.py readme.org")
    print(f"  3. sudo nixos-rebuild switch --flake .")


if __name__ == "__main__":
    main()
