#+title: dimitril NixOS Configuration

See [[install.org]] for installation instructions.

* Table of Contents
- [[file:readme.org][readme.org]]: Master file, user settings, includes
- [[file:flake.org][flake.org]]: Flake configuration
- [[file:system.org][system.org]]: Shared system-level NixOS configuration
- [[file:hosts/default.org][hosts/]]: Per-host configurations (p14s, t14s)
- [[file:home.org][home.org]]: Home-manager entry point
- [[file:modules/core.org][core.org]]: Core shared modules
- [[file:modules/emacs.org][emacs.org]]: Emacs ecosystem
- [[file:modules/apps.org][apps.org]]: Applications and development tools
- [[file:modules/phd.org][phd.org]]: PhD / academic tools
- [[file:modules/xfce/xfce.org][XFCE]]: XFCE desktop environment
- [[file:modules/driftwm/driftwm.org][DriftWM]]: DriftWM compositor

* Quick Links
- [[./boox-palma.org]]
- [[elisp:(org-babel-tangle)][Tangle file]]
- [[elisp:(dl/nixos-update-user-config)][Update home config]]
- [[elisp:(dl/nixos-update-system-config)][Update system config]]
- [[elisp:(dl/nixos-update-all-config)][Update all config]]
- [[elisp:(vterm-nixos-config)][Launch terminal for config]]
-------
- [[*System Packages][configuration.nix packages]]
- [[*home.nix packages inbox][home.nix packages]]
- [[id:93410304-5af5-429b-ab09-18892f0950bc][Nix tasks]]
-----
- [[*Try out python package][Install python package]]

* Inbox
** Emacs versions

This build in particular feels very snappy. Way snappier than what I was using in xfce. Though I haven't figured out to how to get it within the gui.
GNU Emacs 30.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.49, cairo version 1.18.2)

** Emacs Launchers
*** How I am deeply integrating emacs - The Universe of Joshua Blais
:PROPERTIES:
:URL:      https://joshblais.com/blog/how-i-am-deeply-integrating-emacs/
:CREATED:  [2026-01-10 Sat 13:04]
:END:

** screen sharing app
nix run nixpkgs#deskreen

** Update a specific package
#+begin_src bash
cd ~/.dotfiles
nix flake lock --update-input driftwm
home-manager switch --flake .
#+end_src

** Boox tablet (Weylus - recommended)
Weylus works better with Boox over WiFi. Install on Boox from Play Store or F-Droid.

Usage:
1. Run ~weylus-start~ on laptop
2. On Boox: Open Firefox and go to URL shown (http://:1701)
3. Accept connection - tablet becomes drawing tablet

USB (no WiFi):
1. Run: ~adb reverse tcp:1701 tcp:1701 && adb reverse tcp:9001 tcp:9001~
2. On Boox: Open Firefox and go to http://127.0.0.1:1701

Note: droidux had USB issues with Boox.

* Resources
** Common Commands
- Updating:
#+begin_src bash
# Home manager
home-manager switch --flake .
# Switch flakes
sudo nixos-rebuild switch --flake .
# Both
home-manager switch --flake . && sudo nixos-rebuild switch --flake .
# Upgrade packages
sudo nixos-rebuild switch --flake . --upgrade

# don't sleep
systemd-inhibit --what=sleep:idle:shutdown your-command
#+end_src
- Conflicting packages: =nix-env -q=
- Garbage collection: =nix-collect-garbage -d --delete-older-than 10d=
** Literate Config Organization
This is a multi-file literate NixOS configuration powered by Emacs org-mode.

Key files:
- [[file:readme.org][readme.org]]: Master file, user settings, includes
- [[file:flake.org][flake.org]]: Flake configuration
- [[file:system.org][system.org]]: System-level NixOS configuration
- [[file:home.org][home.org]]: Home-manager entry point
- [[file:modules/core.org][modules/core.org]]: Core shared modules
- [[file:modules/emacs.org][modules/emacs.org]]: Emacs ecosystem
- [[file:modules/apps.org][modules/apps.org]]: Applications and development tools
- [[file:modules/phd.org][modules/phd.org]]: PhD / academic tools
- [[file:modules/xfce/xfce.org][modules/xfce/xfce.org]]: XFCE desktop environment
- [[file:modules/driftwm/driftwm.org][modules/driftwm/driftwm.org]]: DriftWM compositor

To tangle:
#+begin_src bash
./sync.sh
#+end_src

Or manually:
#+begin_src bash
# With Python (default)
python3 tangle.py readme.org
# With Emacs batch mode
emacs --batch -l org -f org-babel-tangle-file readme.org
# With Doom Emacs
doom +org tangle readme.org
#+end_src
* User Settings
#+begin_src nix :noweb-ref userSettings
userSettings = {
username = "dimitril";
name = "Dimitri";
email = "dimitrilopez01@gmail.com";
dotfilesDir = "~/.dotfiles"; # absolute path of the local repo
};
#+end_src
* System Settings
#+begin_src nix :noweb-ref systemSettings
systemSettings = {
system = "x86_64-linux"; # system arch
};
#+end_src

* Configuration Entry Point
** System base imports (configuration.nix)
Always included regardless of wm setting:
#+begin_src nix :noweb-ref configuration.nix-imports
imports =
[
  ./modules/kanata.nix
  ./modules/steam.nix
  ./system/bluetooth.nix
  ./system/pipewire.nix
  ./system/syncthing.nix
];
#+end_src

** Home base imports (home.nix)
Always included regardless of wm setting:
#+begin_src nix :noweb-ref home.nix.imports
imports = let
  hostname = lib.strings.fileContents /etc/hostname;
in [
  ./modules/common.nix
  ./modules/git.nix
  ./modules/phd.nix
  ./modules/python.nix
  ./modules/sh.nix
  ./modules/scripting.nix
  ./modules/emacs.nix
  ./modules/brave.nix
  ./modules/minecraft.nix
  ./modules/watchy.nix
  ./modules/mcp-nixos.nix
  ./modules/llms.nix
] ++ lib.optionals (hostname == "p14s" || hostname == "t14s") [
  ./modules/driftwm/home.nix
];
#+end_src

* Tangling
#+INCLUDE: ./flake.org
#+INCLUDE: ./system.org
#+INCLUDE: ./home.org
#+INCLUDE: ./hosts/default.org
#+INCLUDE: ./modules/core.org
#+INCLUDE: ./modules/emacs.org
#+INCLUDE: ./modules/apps.org
#+INCLUDE: ./modules/llms.org
#+INCLUDE: ./modules/phd.org
#+INCLUDE: ./modules/xfce/xfce.org
#+INCLUDE: ./modules/driftwm/driftwm.org
