#+title: dimitril NixOS Configuration

See [[install.org]] for installation instructions.

* Table of Contents
- [[file:readme.org][readme.org]]: Master file, user settings, includes
- [[file:flake.org][flake.org]]: Flake configuration
- [[file:system.org][system.org]]: System-level NixOS configuration
- [[file:home.org][home.org]]: Home-manager entry point
- [[file:modules/core.org][core.org]]: Core shared modules
- [[file:modules/emacs.org][emacs.org]]: Emacs ecosystem
- [[file:modules/apps.org][apps.org]]: Applications and development tools
- [[file:modules/phd.org][phd.org]]: PhD / academic tools
- [[file:modules/xfce/xfce.org][XFCE]]: XFCE desktop environment
- [[file:modules/driftwm/driftwm.org][DriftWM]]: DriftWM compositor

* Inbox
** Emacs versions

This build in particular feels very snappy. Way snappier than what I was using in xfce. Though I haven't figured out to how to get it within the gui.
GNU Emacs 30.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.49, cairo version 1.18.2)

* Resources
** Common Commands
- Updating:
  #+begin_src bash
# Home manager
home-manager switch --flake .
# Switch flakes
sudo nixos-rebuild switch --flake .
# Both
home-manager switch --flake . && sudo nixos-rebuild switch --flake .
# Upgrade packages
sudo nixos-rebuild switch --flake . --upgrade
  #+end_src
- Conflicting packages: =nix-env -q=
- Garbage collection: =nix-collect-garbage -d --delete-older-than 10d=
** Literate Config Organization
This is a multi-file literate NixOS configuration powered by Emacs org-mode.

Key files:
- [[file:readme.org][readme.org]]: Master file, user settings, includes
- [[file:flake.org][flake.org]]: Flake configuration
- [[file:system.org][system.org]]: System-level NixOS configuration
- [[file:home.org][home.org]]: Home-manager entry point
- [[file:modules/core.org][modules/core.org]]: Core shared modules
- [[file:modules/emacs.org][modules/emacs.org]]: Emacs ecosystem
- [[file:modules/apps.org][modules/apps.org]]: Applications and development tools
- [[file:modules/phd.org][modules/phd.org]]: PhD / academic tools
- [[file:modules/xfce/xfce.org][modules/xfce/xfce.org]]: XFCE desktop environment
- [[file:modules/driftwm/driftwm.org][modules/driftwm/driftwm.org]]: DriftWM compositor

To tangle:
#+begin_src bash
./sync.sh
#+end_src

Or manually:
#+begin_src bash
# With Python (default)
python3 tangle.py readme.org
# With Emacs batch mode
emacs --batch -l org -f org-babel-tangle-file readme.org
# With Doom Emacs
doom +org tangle readme.org
#+end_src
* User Settings
#+begin_src nix :noweb-ref userSettings
userSettings = {
  username = "dimitril";
  name = "Dimitri";
  email = "dimitrilopez01@gmail.com";
  dotfilesDir = "~/.dotfiles"; # absolute path of the local repo
  # Options: "xfce", "driftwm" - desktop modules auto-loaded in flake.nix
  wm = "driftwm";
};
#+end_src
* System Settings
#+begin_src nix :noweb-ref systemSettings
systemSettings = {
  system = "x86_64-linux"; # system arch
  hostname = "dimitril-hostname";   # hostname
};
#+end_src

* Configuration Entry Point
** System base imports (configuration.nix)
Always included regardless of wm setting:
#+begin_src nix :noweb-ref configuration.nix-imports
imports =
  [ # Include the results of the hardware scan.
    ./hardware-configuration.nix

    ./modules/kanata.nix
    ./modules/steam.nix
    ./system/bluetooth.nix
    ./system/pipewire.nix
    ./system/syncthing.nix
  ];
#+end_src

** Home base imports (home.nix)
Always included regardless of wm setting:
#+begin_src nix :noweb-ref home.nix.imports
imports = [
  ./modules/common.nix
  ./modules/git.nix
  ./modules/phd.nix
  ./modules/python.nix
  ./modules/sh.nix
  ./modules/scripting.nix
  ./modules/emacs.nix
  ./modules/brave.nix
  ./modules/minecraft.nix
  ./modules/watchy.nix
  ./modules/mcp-nixos.nix
];
#+end_src

* Tangling
#+INCLUDE: ./flake.org
#+INCLUDE: ./system.org
#+INCLUDE: ./home.org
#+INCLUDE: ./modules/core.org
#+INCLUDE: ./modules/emacs.org
#+INCLUDE: ./modules/apps.org
#+INCLUDE: ./modules/phd.org
#+INCLUDE: ./modules/xfce/xfce.org
#+INCLUDE: ./modules/driftwm/driftwm.org
