{ pkgs, lib, inputs, ... }:

{
  imports = [
    ./alacritty.nix
    ./kitty.nix
  ];
  wayland.windowManager.hyprland = {
    enable = true;
    #   # package = pkgs-hyprland.hyprland-minimal;
    #   # plugins = [ ];
    #   # settings = { };
    extraConfig = ''
autogenerated = 0 # remove this line to remove the warning

# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf
# See https://wiki.hyprland.org/Configuring/Monitors/
# default onitor seeing
# monitor=,preferred,auto,auto
monitor = ,preferred,auto,1
# # thinkpad monitor
# monitor = desc: AU Optronics 0x573D,
# # dell monitor
# monitor = desc: Dell Inc. DELL P3421W,
# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun
# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = systemctl --user restart gvfs-daemon # needed for tramp emacs
exec-once = dropbox
# exec-once = blueman-applet # TODO Need to double check if this is needed

exec-once = hyprsunset
exec-once = hyprpaper
exec-once = hypridle
# exec-once = waybar

exec-once = sleep 1 && restart-emacs-daemon
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}
# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}
# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = yes, please :)

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
}

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]
# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}
# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}
# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}
# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 0
    kb_options = ctrl:nocaps

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
    repeat_delay = 185
    repeat_rate = 75
}
# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = false
}
# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
# See https://wiki.hyprland.org/Configuring/Keywords/
$mainMod = SUPER # Sets "Super" key as main modifier
bindm = SUPER, mouse:274, togglefloating
bind = SUPER_L&ALT_L, mouse:272, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | grep float | awk '{print $2 + 0.1}')"
bind = SUPER_L&ALT_L, mouse:273, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | grep float | awk '{print $2 - 0.1}')"
bind = SUPER, F, fullscreen, 1
# bind = SUPERSHIFT, F, fullscreen, 0
bind = SUPER, B, togglefloating
bind=SUPER,Y,workspaceopt,allfloat
bind = ALT, W, fullscreen
bind = ,W&L, fullscreen
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = SUPER, SPACE, exec, nwggrid
bind = SUPER, D, exec, nwggrid
# bind = SUPER, T, exec, $terminal

# brave
bind = SUPER, C, exec, raise --class "Brave-browser" --launch "brave"
bind = ,J&B, exec, raise --class "Brave-browser" --launch "brave"
# bind = SUPER_SHIFT, C, exec, brave
# bind = SUPER, C, exec, brave

bind = SUPER, T, exec, raise --class "Alacritty" --launch "alacritty"
bind = SUPER_SHIFT, T, exec, alacritty

bind = $mainMod, X, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
# bind = $mainMod, J, togglesplit, # dwindle
bind=SUPER,S,exec,grim -g "$(slurp)" - | wl-copy
# bind=,code:107,exec,grim -g "$(slurp)"
# bind=SHIFT,code:107,exec,grim -g "$(slurp -o)"
# bind=SUPER,code:107,exec,grim
# bind=CTRL,code:107,exec,grim -g "$(slurp)" - | wl-copy
# bind=SHIFTCTRL,code:107,exec,grim -g "$(slurp -o)" - | wl-copy
# bind=SUPERCTRL,code:107,exec,grim - | wl-copy
# emacs
bind = ALT, E, exec, raise --class "Emacs" --launch "emacsclient --create-frame"
bind = ,J&E, exec, raise --class "Emacs" --launch "emacsclient --create-frame"
bind = SUPER, E, exec, raise --class "Emacs" --launch "emacsclient --create-frame"
bind = SUPER_SHIFT, E, exec, emacsclient --create-frame
bind = SUPER, I, exec, emacsclient --eval "(emacs-everywhere)" # TODO
bind = SUPER, BackSpace, exec, /home/dimitril/.config/emacs/bin/org-capture
# bind = ALT, E, exec, emacsclient -c
# bind = SUPER, E, exec, emacsclient -c
# restart emacs daemon
bind = SUPER, 0, exec, restart-emacs-daemon
bind = SUPER_SHIFT, C, exec, wl-copy $(hyprpicker)
bind = SUPERALT, T, exec, screenshot-ocr
# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# alt tab
bind=ALT,TAB,cyclenext
bind=ALT,TAB,bringactivetotop
bind=ALTSHIFT,TAB,cyclenext,prev
bind=ALTSHIFT,TAB,bringactivetotop

# Move focus with arrow keys
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

# Move focus with vim keybindings as well
bind=SUPER,H,movefocus,l
bind=SUPER,J,movefocus,d
bind=SUPER,K,movefocus,u
bind=SUPER,L,movefocus,r
bind=SUPER,H,alterzorder,top
bind=SUPER,L,alterzorder,top
bind=SUPER,K,alterzorder,top
bind=SUPER,J,alterzorder,top

# Move where windows are
bind=SUPERSHIFT,H,movewindow,l
bind=SUPERSHIFT,J,movewindow,d
bind=SUPERSHIFT,K,movewindow,u
bind=SUPERSHIFT,L,movewindow,r

# Move where windows are
bind=SUPER&ALT,H,movewindow,l
bind=SUPER&ALT,J,movewindow,d
bind=SUPER&ALT,K,movewindow,u
bind=SUPER&ALT,L,movewindow,r

# Kill window while on vim keybindings
bind=SUPER,ESCAPE,killactive,

# Scroll through existing workspaces with mainMod + scroll
# bind = $mainMod, mouse_down, workspace, e+1
# bind = $mainMod, mouse_up, workspace, e-1

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
# Example special workspace (scratchpad)
# bind = $mainMod, S, togglespecialworkspace, magic
# bind = $mainMod SHIFT, S, movetoworkspace, special:magic



# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Have windows be floating by default
windowrulev2 = float, class:.*
# Have the following windows be tiled by default
windowrulev2 = tile, class:^(Emacs) # TODO
windowrulev2 = float, title:^(doom-capture) # TODO
windowrulev2 = tile, class:^(Brave-browser) # TODO
windowrulev2 = tile, class:^(Alacritty)
windowrulev2 = tile, class:^(thunar)
windowrulev2 = float,class:^(steam)

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
    '';
    #   xwayland.enable = true;
    #   # systemd.enable = true;
  };

  home.packages = with pkgs; [
    alacritty # fancy terminal
    kitty # default terminal
    waybar # bar, switch to eww later
    dunst # notifications
    libnotify # dunst dependency
    swww # wallpaper manager

    nwg-launchers # app launcher
    rofi-wayland # application launcher
    nwg-displays # display manager
    playerctl # for audio controls

    hyprlock # lock manager
    brightnessctl # used for dimming brightness
    hyprsunset # bluelight filter
    hyprpaper # wallpaper
    # redshift # blue light filter
    # geoclue2 # red shift dependency
    vim  # basic text editor
    dropbox # syncing files
    blueman # bluetooth
    xfce.xfce4-taskmanager
    xfce.thunar

    # cli tools
    hyprpicker # color picker
    wl-clipboard # clipboard manager

    tesseract4 # ocr
    slurp # screenshot
    grim # used to grab images?
    wev # used to find keybindings
    (pkgs.writeScriptBin "screenshot-ocr" ''
      #!/bin/sh
      imgname="/tmp/screenshot-ocr-$(date +%Y%m%d%H%M%S).png"
      txtname="/tmp/screenshot-ocr-$(date +%Y%m%d%H%M%S)"
      txtfname=$txtname.txt
      grim -g "$(slurp)" $imgname;
      tesseract $imgname $txtname;
      wl-copy -n < $txtfname
    '')


  ] ++ [ inputs.raise.defaultPackage.x86_64-linux ];
  
  home.file.".config/hypr/hyprpaper.conf".text = ''
  preload = /home/dimitril/Dropbox/images/Truchas_LopezRanch_MW.jpg
  wallpaper = monitor, /home/dimitril/Dropbox/images/Truchas_LopezRanch_MW.jpg
  '';
  
  home.file.".config/hypr/hyprlock.conf".text = ''
  background {
  monitor =
  path = screenshot
  blur_passes = 4
  blur_size = 5
  noise = 0.0117
  contrast = 0.8916
  brightness = 0.8172
  vibrancy = 0.1696
  vibrancy_darkness = 0.0
  }
  image {
  monitor =
  path = /home/dimitril/Dropbox/images/Truchas_LopezRanch_MW.jpg
  size = 150 # lesser side if not 1:1 ratio
  rounding = -1 # negative values mean circle
  border_size = 0
  rotate = 0 # degrees, counter-clockwise
  
  position = 0, 200
  halign = center
  valign = center
  }
  
  input-field {
  monitor =
  size = 200, 50
  outline_thickness = 3
  dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
  dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
  dots_center = false
  dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
  fade_on_empty = true
  fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
  placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
  hide_input = false
  rounding = -1 # -1 means complete rounding (circle/oval)
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
  fail_transition = 300 # transition time in ms between normal outer_color and fail_color
  capslock_color = -1
  numlock_color = -1
  bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
  invert_numlock = false # change color if numlock is off
  swap_font_color = false # see below
  
  position = 0, -20
  halign = center
  valign = center
  }
  
  label {
  monitor =
  text = Hello, dimitril
  rotate = 0 # degrees, counter-clockwise
  
  position = 0, 160
  halign = center
  valign = center
  }
  
  label {
  monitor =
  text = $TIME
  rotate = 0 # degrees, counter-clockwise
  
  position = 0, 80
  halign = center
  valign = center
  }
  
  
  '';
  
  home.file.".config/hypr/hypridle.conf".text = ''
  general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    ignore_dbus_inhibit = false
  }
  
  # Reduce brightness
  listener {
      timeout = 150                                # 2.5min.
      on-timeout = brightnessctl -s set 5          # set monitor backlight to minimum, avoid 0 on OLED monitor.
      on-resume = brightnessctl -r                 # monitor backlight restore.
  }
  
  # Turn off keyboard backlight
  listener {
      timeout = 150                                              # 2.5min.
      on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 0 # turn off keyboard backlight.
      on-resume = brightnessctl -rd tpacpi::kbd_backlight        # turn on keyboard backlight.
  }
  
  # FIXME memory leak fries computer inbetween dpms off and suspend
  #listener {
  #  timeout = 150 # in seconds
  #  on-timeout = hyprctl dispatch dpms off
  #  on-resume = hyprctl dispatch dpms on
  #}
  listener {
    timeout = 165 # in seconds
    on-timeout = loginctl lock-session
  }
  listener {
    timeout = 180 # in seconds
    #timeout = 5400 # in seconds
    on-timeout = systemctl suspend
    on-resume = hyprctl dispatch dpms on
  }
  
  listener {
      timeout = 300                                 # 5min
      on-timeout = loginctl lock-session            # lock screen when timeout has passed
  }
  
  listener {
      timeout = 330                                                     # 5.5min
      on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
      on-resume = hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
  }
  
  listener {
      timeout = 400                                # 30min
      on-timeout = systemctl suspend                # suspend pc
  }
  '';
  
}
